# Source unique des recettes ajoutées à l'étape 1 (10 plats + 7 petits-déjeuners).
# Low carb strict : glucides nets <= 30 g par portion (estimations).
# ingredients : quantités pour tout le batch (meals repas pour 2) ; layers : pile dessinée (bas -> haut),
# [refs "ingredient:pose" (+ séparés), étiquette, note]. layers vide = pile de repli.
B, P, L, C, E = "Boucherie", "Poissonnerie", "Légumes", "Crèmerie", "Épicerie"

RECIPES = [
 # ---------------- plats ----------------
 dict(id="r31-saumon-pesto-rouge-haricots", comp="saumon-pesto-haricots", name="Saumon au pesto rouge, haricots plats",
  meal_type="main", protein="poisson", time_min=25, meals=2, carbs=9, prot=36, kcal=520, tags=["four", "réchauffable"],
  tagline="Laqué. Piquant. Croquant.",
  ingredients=[["pavé de saumon",4,"pièce",P],["haricots plats",600,"g",L],["pesto rouge",4,"c. à s.",E],["jalapeños en bocal",40,"g",E],["parmesan râpé",40,"g",C],["herbes de Provence",1,"c. à c.",E]],
  steps=["Four 200 °C. Haricots plats 6 min à l'eau bouillante, égouttés.","Pavés sur plaque, badigeonnés de pesto rouge, herbes.","12 min au four, haricots autour les 5 dernières minutes.","Jalapeños et parmesan au service."],
  layers=[["haricots-verts:plat","Haricots plats","Blanchis, encore fermes."],["saumon-pave:plat","Pavé de saumon","Rosé à cœur."],["sauce-tomate:eparpille","Pesto rouge","Badigeonné avant le four."],["poivron:eparpille","Jalapeños","Pour réveiller."],["fromage-rape:eparpille","Parmesan","Juste un voile."]]),
 dict(id="r32-tajine-poulet-citron-olives", comp="tajine-poulet-citron", name="Tajine de poulet, citron et olives",
  meal_type="main", protein="poulet", time_min=50, meals=3, carbs=8, prot=40, kcal=510, tags=["batch", "réchauffable", "dimanche"],
  tagline="Mijoté. Acidulé. Parfumé.",
  ingredients=[["hauts de cuisse de poulet",1.2,"kg",B],["oignon",2,"pièce",L],["olives vertes",150,"g",E],["citron confit",1,"pièce",E],["bouillon de volaille",300,"ml",E],["gingembre moulu",1,"c. à c.",E],["curcuma",1,"c. à c.",E],["coriandre",1,"botte",L]],
  steps=["Dorer le poulet, réserver.","Oignons émincés 8 min, épices 1 min.","Remettre le poulet, bouillon, citron confit en lanières ; 30 min à couvert.","Olives les 10 dernières minutes, coriandre au service."],
  layers=[["bouillon:plat","Le jus","Épicé, réduit à couvert."],["poulet-cuisse:tas","Hauts de cuisse","Dorés avant de mijoter."],["oignon:eparpille","Oignons","Fondus, pas colorés."],["citron-quartier:eparpille","Citron confit","L'acidité du plat."],["coriandre:eparpille","Coriandre","La pluie."]]),
 dict(id="r33-keftas-boeuf-concombre-feta", comp="keftas-concombre-feta", name="Keftas de bœuf, concombre-feta",
  meal_type="main", protein="boeuf", time_min=30, meals=2, carbs=7, prot=38, kcal=560, tags=["réchauffable", "froid"],
  tagline="Grillé. Épicé. Frais.",
  ingredients=[["bœuf haché 5%",800,"g",B],["oignon",1,"pièce",L],["persil",1,"botte",L],["cumin",2,"c. à c.",E],["concombre",2,"pièce",L],["feta",150,"g",C],["yaourt grec",200,"g",C]],
  steps=["Keftas : bœuf, oignon râpé, persil haché, cumin, sel ; former des boudins.","Poêle très chaude, 8 min en les roulant.","Concombre en dés, feta émiettée, yaourt citronné à côté."],
  layers=[["creme-yaourt:plat","Yaourt grec","Citronné, bien froid."],["boulette:tas","Keftas","Cumin, persil, feu vif."],["concombre:eparpille","Concombre","En dés, pour la fraîcheur."],["feta:eparpille","Feta","Émiettée au dernier moment."],["persil:eparpille","Persil","La pluie."]]),
 dict(id="r34-filet-mignon-soja-haricots", comp="filet-mignon-soja-sesame", name="Filet mignon soja-gingembre, haricots sésame",
  meal_type="main", protein="porc", time_min=30, meals=2, carbs=9, prot=38, kcal=470, tags=["réchauffable", "rapide"],
  tagline="Laqué. Rosé. Toasté.",
  ingredients=[["filet mignon de porc",700,"g",B],["haricots verts",500,"g",L],["sauce soja",4,"c. à s.",E],["gingembre",30,"g",L],["ail",2,"gousse",L],["graines de sésame",2,"c. à s.",E]],
  steps=["Filet mignon saisi sur toutes les faces, puis 12 min à 180 °C.","Haricots vapeur 8 min, sautés à l'ail.","Laquer le filet avec soja et gingembre râpé, trancher, sésame toasté dessus."],
  layers=[["haricots-verts:plat","Haricots verts","Vapeur puis poêle."],["filet-mignon:tas","Filet mignon","Rosé, tranché épais."],["sauce-soja:eparpille","Laque soja","Réduite dans la poêle."],["gingembre:eparpille","Gingembre","Râpé frais."],["sesame:eparpille","Sésame","Toasté à sec."]]),
 dict(id="r35-cabillaud-croute-parmesan", comp="cabillaud-croute-parmesan", name="Cabillaud en croûte de parmesan, champignons",
  meal_type="main", protein="poisson", time_min=25, meals=1, carbs=5, prot=38, kcal=420, tags=["four", "rapide"],
  tagline="Gratiné. Nacré. Boisé.",
  ingredients=[["dos de cabillaud",2,"pièce",P],["parmesan râpé",50,"g",C],["poudre d'amande",30,"g",E],["champignons de Paris",250,"g",L],["épinards frais",200,"g",L],["beurre",20,"g",C]],
  steps=["Four 200 °C. Croûte : parmesan, poudre d'amande, beurre mou.","Étaler sur le cabillaud, 12 min au four.","Champignons à feu vif, épinards tombés 2 min dans la même poêle."],
  layers=[["epinards:plat","Épinards","Tombés, pas cuits."],["champignons:eparpille","Champignons","Feu vif, sans les remuer."],["cabillaud:plat","Cabillaud","Nacré sous la croûte."],["fromage-rape:eparpille","Croûte parmesan","Parmesan et amande."],["persil:eparpille","Persil","La pluie."]]),
 dict(id="r36-chili-blanc-dinde", comp="chili-blanc-dinde", name="Chili blanc de dinde",
  meal_type="main", protein="dinde", time_min=40, meals=3, carbs=10, prot=40, kcal=470, tags=["batch", "réchauffable"],
  tagline="Crémeux. Doux. Réconfortant.",
  ingredients=[["dinde hachée",900,"g",B],["poivron vert",2,"pièce",L],["oignon",2,"pièce",L],["courgette",2,"pièce",L],["bouillon de volaille",300,"ml",E],["crème",200,"ml",C],["cumin",2,"c. à c.",E],["coriandre",1,"botte",L]],
  steps=["Oignons et poivrons 6 min.","Dinde, colorer 5 min, cumin.","Courgettes en dés, bouillon ; 20 min.","Crème hors du feu, coriandre au service."],
  layers=[["bouillon:plat","Le fond","Bouillon et crème."],["dinde-hachee:plat","Dinde hachée","Colorée avant le bouillon."],["poivron:eparpille","Poivrons verts","Doux, pas piquants."],["courgette-rondelles:eparpille","Courgette","Pour le volume."],["coriandre:eparpille","Coriandre","La pluie."]]),
 dict(id="r37-aubergines-farcies-boeuf-feta", comp="aubergines-farcies-feta", name="Aubergines farcies bœuf-feta",
  meal_type="main", protein="boeuf", time_min=55, meals=2, carbs=12, prot=34, kcal=520, tags=["four", "réchauffable"],
  tagline="Fondant. Farci. Gratiné.",
  ingredients=[["aubergine",3,"pièce",L],["bœuf haché 5%",600,"g",B],["tomates concassées",400,"g",E],["oignon",1,"pièce",L],["feta",150,"g",C],["persil",1,"botte",L]],
  steps=["Four 200 °C. Aubergines coupées en deux, chair quadrillée, 25 min.","Farce : oignon, bœuf, tomates, chair d'aubergine ; 10 min.","Remplir, feta dessus, 15 min au four. Persil au service."],
  layers=[["sauce-tomate:plat","Sauce tomate","Le lit des aubergines."],["aubergine:plat","Aubergine","Rôtie avant d'être farcie."],["boeuf-hache:eparpille","Farce de bœuf","Avec la chair d'aubergine."],["feta:eparpille","Feta","Gratinée au four."],["persil:eparpille","Persil","La pluie."]]),
 dict(id="r38-salade-lardons-oeuf-chevre", comp="salade-lardons-oeuf-chevre", name="Salade tiède lardons, œuf poché, chèvre",
  meal_type="main", protein="porc", time_min=15, meals=1, carbs=5, prot=28, kcal=520, tags=["rapide", "lunch"],
  tagline="Tiède. Coulant. Croquant.",
  ingredients=[["salade verte",1,"pièce",L],["lardons",150,"g",B],["œufs",4,"pièce",C],["chèvre frais",100,"g",C],["moutarde",1,"c. à s.",E],["vinaigre de vin",2,"c. à s.",E]],
  steps=["Lardons dorés à sec.","Œufs pochés 3 min dans l'eau vinaigrée frémissante.","Salade, vinaigrette moutarde, lardons chauds, chèvre, œufs dessus."],
  layers=[["laitue:plat","Salade","Vinaigrette moutarde."],["lardons:eparpille","Lardons","Chauds, sur le froid."],["chevre:eparpille","Chèvre frais","En morceaux."],["oeuf-poche:eparpille","Œuf poché","Trois minutes."],["persil:eparpille","Persil","La pluie."]]),
 dict(id="r39-bowl-tofu-avocat-brocoli", comp="bowl-tofu-avocat", name="Bowl tofu, avocat, brocoli sésame",
  meal_type="main", protein="vege", time_min=20, meals=1, carbs=11, prot=26, kcal=480, tags=["végé", "rapide", "lunch"],
  tagline="Vert. Croustillant. Frais.",
  ingredients=[["tofu ferme",400,"g",C],["brocoli",1,"tête",L],["avocat",1,"pièce",L],["sauce soja",3,"c. à s.",E],["graines de sésame",1,"c. à s.",E],["citron vert",1,"pièce",L]],
  steps=["Tofu pressé, en cubes, poêle très chaude 8 min.","Brocoli vapeur 5 min.","Avocat en tranches, soja-citron vert, sésame."],
  layers=[["brocoli:plat","Brocoli","Vapeur, encore vert."],["tofu:tas","Tofu","Croustillant sur toutes les faces."],["avocat:eparpille","Avocat","Tranché au dernier moment."],["sauce-soja:eparpille","Soja-citron vert","La sauce."],["sesame:eparpille","Sésame","La pluie."]]),
 dict(id="r40-poulet-citron-poireaux", comp="poulet-citron-poireaux", name="Poulet au citron, poireaux fondants",
  meal_type="main", protein="poulet", time_min=40, meals=2, carbs=10, prot=40, kcal=490, tags=["réchauffable"],
  tagline="Doux. Citronné. Fondant.",
  ingredients=[["blanc de poulet",800,"g",B],["poireau",3,"pièce",L],["crème",150,"ml",C],["citron",1,"pièce",L],["thym",1,"botte",L],["beurre",20,"g",C]],
  steps=["Poireaux émincés, 15 min à couvert dans le beurre.","Poulet en morceaux doré à part.","Réunir, crème, zeste et jus de citron, thym ; 10 min."],
  layers=[["poireau:plat","Poireaux","Fondus au beurre."],["creme-yaourt:eparpille","Crème","Juste pour lier."],["poulet-blanc:tas","Blanc de poulet","Doré avant la crème."],["citron-rondelle:eparpille","Citron","Zeste et jus."],["persil:eparpille","Thym","Frais, effeuillé."]]),
 # ---------------- petits-déjeuners (pour 2, une matinée) ----------------
 dict(id="r41-oeufs-epinards-pain-complet", comp="petitdej-oeufs-epinards", name="Œufs brouillés aux épinards, pain complet",
  meal_type="breakfast", protein="oeufs", time_min=10, meals=1, carbs=14, prot=22, kcal=380, tags=["petit-déj"],
  tagline="Soyeux. Vert. Rassasiant.",
  ingredients=[["œufs",5,"pièce",C],["épinards frais",150,"g",L],["beurre",10,"g",C],["pain complet",2,"tranche",E]],
  steps=["Épinards tombés au beurre 1 min.","Œufs battus, cuisson douce en remuant.","Une tranche de pain complet grillée chacun."],
  layers=[["epinards:plat","Épinards","Une minute au beurre."],["oeufs-brouilles:tas","Œufs brouillés","Feu doux, retirés tôt."],["persil:eparpille","Ciboulette","La pluie."]]),
 dict(id="r42-shaker-proteine-cacao", comp=None, name="Shaker protéiné cacao-cacahuète",
  meal_type="breakfast", protein="vege", time_min=3, meals=1, carbs=7, prot=30, kcal=300, tags=["petit-déj", "rapide"],
  tagline="Froid. Rapide. Costaud.",
  ingredients=[["lait d'amande sans sucre",500,"ml",C],["protéine en poudre (whey)",60,"g",E],["beurre de cacahuète",2,"c. à s.",E],["cacao non sucré",1,"c. à s.",E]],
  steps=["Tout dans le shaker avec des glaçons.","Secouer 20 secondes."],
  layers=[]),
 dict(id="r43-yaourt-grec-graines-framboises", comp="petitdej-yaourt-graines", name="Yaourt grec, graines et framboises",
  meal_type="breakfast", protein="vege", time_min=5, meals=1, carbs=13, prot=22, kcal=330, tags=["petit-déj", "froid"],
  tagline="Frais. Croquant. Acidulé.",
  ingredients=[["yaourt grec",400,"g",C],["framboises",125,"g",L],["graines de chia",2,"c. à s.",E],["graines de courge",2,"c. à s.",E],["amandes effilées",2,"c. à s.",E]],
  steps=["Yaourt dans deux bols.","Framboises, graines et amandes dessus."],
  layers=[["creme-yaourt:plat","Yaourt grec","Le plus épais possible."],["sesame:eparpille","Chia et courge","Les graines."],["amandes:eparpille","Amandes","Effilées, grillées si le temps."]]),
 dict(id="r44-bol-graines-chocolat-goji", comp="petitdej-bol-graines", name="Bol yaourt, graines, chocolat noir et goji",
  meal_type="breakfast", protein="vege", time_min=5, meals=1, carbs=18, prot=20, kcal=420, tags=["petit-déj", "froid"],
  tagline="Rangé. Croquant. Gourmand.",
  ingredients=[["yaourt grec",400,"g",C],["graines de chia",2,"c. à s.",E],["graines de courge",2,"c. à s.",E],["graines de tournesol",2,"c. à s.",E],["chocolat noir 85 %",30,"g",E],["baies de goji",20,"g",E]],
  steps=["Yaourt dans deux bols.","Rangées de garnitures : chocolat, chia, courge et tournesol, goji."],
  layers=[["creme-yaourt:plat","Yaourt grec","La base."],["sesame:tas","Chia et tournesol","Rangés, pas mélangés."],["amandes:eparpille","Graines de courge","Pour le croquant."]]),
 dict(id="r45-omelette-jambon-fromage", comp="petitdej-omelette-jambon", name="Omelette jambon-fromage",
  meal_type="breakfast", protein="porc", time_min=10, meals=1, carbs=2, prot=30, kcal=420, tags=["petit-déj", "rapide"],
  tagline="Dorée. Filante. Simple.",
  ingredients=[["œufs",5,"pièce",C],["jambon blanc",2,"tranche",B],["fromage râpé",50,"g",C],["beurre",10,"g",C]],
  steps=["Œufs battus, beurre moussant.","Jambon et fromage au centre, plier."],
  layers=[["omelette:plat","Omelette","Baveuse au centre."],["jambon:eparpille","Jambon","En lanières."],["fromage-rape:eparpille","Fromage","Qui file."],["persil:eparpille","Ciboulette","La pluie."]]),
 dict(id="r46-avocat-oeufs-mollets-saumon", comp="petitdej-avocat-saumon", name="Avocat, œufs mollets, saumon fumé",
  meal_type="breakfast", protein="poisson", time_min=10, meals=1, carbs=4, prot=24, kcal=450, tags=["petit-déj"],
  tagline="Fondant. Fumé. Frais.",
  ingredients=[["avocat",2,"pièce",L],["œufs",4,"pièce",C],["saumon fumé",100,"g",P],["citron",1,"pièce",L],["aneth",0.5,"botte",L]],
  steps=["Œufs 6 min dans l'eau bouillante, puis eau froide.","Avocat en tranches, citron, saumon, œufs coupés en deux, aneth."],
  layers=[["avocat:plat","Avocat","Citronné tout de suite."],["saumon-fume:eparpille","Saumon fumé","En pétales."],["oeuf-entier:eparpille","Œufs mollets","Six minutes."],["aneth:eparpille","Aneth","La pluie."]]),
 dict(id="r47-oeufs-tomates-feta", comp="petitdej-oeufs-tomates-feta", name="Œufs au plat, tomates cerises et feta",
  meal_type="breakfast", protein="oeufs", time_min=10, meals=1, carbs=6, prot=20, kcal=360, tags=["petit-déj"],
  tagline="Solaire. Coulant. Salé.",
  ingredients=[["œufs",4,"pièce",C],["tomates cerises",200,"g",L],["feta",80,"g",C],["huile d'olive",1,"c. à s.",E],["origan",1,"pincée",E]],
  steps=["Tomates cerises à l'huile 4 min à feu vif.","Casser les œufs entre les tomates, couvrir 3 min.","Feta émiettée, origan."],
  layers=[["tomates-cerises:plat","Tomates cerises","Éclatées à feu vif."],["oeuf-poche:eparpille","Œufs au plat","Couverts, jaune coulant."],["feta:eparpille","Feta","Émiettée."],["persil:eparpille","Origan","La pluie."]]),
]
