-- Lowtable — schéma Supabase. À coller dans SQL Editor → Run (une seule fois).
-- 1) Remplace les deux emails du foyer ci-dessous avant d'exécuter.

create table if not exists public.household_members (
  email text primary key,
  added_at timestamptz not null default now()
);
insert into public.household_members (email) values
  ('mickael@example.com'),
  ('madame@example.com')
on conflict do nothing;

create table if not exists public.recipes (
  id text primary key,
  name text not null,
  protein text not null,
  time_min int not null default 30,
  meals int not null default 1,
  carbs int not null default 0,
  prot int not null default 0,
  kcal int not null default 0,
  tags text[] not null default '{}',
  ingredients jsonb not null default '[]',
  steps text[] not null default '{}',
  active boolean not null default true,
  source text not null default 'perso',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plans (
  week text primary key,
  slots jsonb not null default '{}',
  locked jsonb not null default '{}',
  checked jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

-- Sécurité : seules les personnes du foyer (connectées par lien magique) lisent et écrivent.
create or replace function public.is_household_member()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.household_members where email = lower(coalesce(auth.jwt() ->> 'email', '')));
$$;

alter table public.household_members enable row level security;
alter table public.recipes enable row level security;
alter table public.plans enable row level security;

drop policy if exists members_read on public.household_members;
create policy members_read on public.household_members for select to authenticated using (public.is_household_member());

drop policy if exists recipes_all on public.recipes;
create policy recipes_all on public.recipes for all to authenticated using (public.is_household_member()) with check (public.is_household_member());

drop policy if exists plans_all on public.plans;
create policy plans_all on public.plans for all to authenticated using (public.is_household_member()) with check (public.is_household_member());

-- Temps réel : les deux téléphones voient les changements de l'autre.
do $$ begin
  alter publication supabase_realtime add table public.recipes;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.plans;
exception when duplicate_object then null; end $$;

-- Les 30 recettes de départ (low carb, sans chou-fleur, orientées batch).
insert into public.recipes (id,name,protein,time_min,meals,carbs,prot,kcal,tags,ingredients,steps,active,source) values
('r01-chili-con-carne-low-carb','Chili con carne low carb','boeuf',40,3,14,38,520,array['batch','réchauffable']::text[],'[{"name": "bœuf haché 5%", "qty": 900, "unit": "g", "rayon": "Boucherie"}, {"name": "poivron rouge", "qty": 3, "unit": "pièce", "rayon": "Légumes"}, {"name": "courgette", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "tomates concassées", "qty": 800, "unit": "g", "rayon": "Épicerie"}, {"name": "cumin", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "paprika fumé", "qty": 1, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "cheddar râpé", "qty": 150, "unit": "g", "rayon": "Crèmerie"}]'::jsonb,array['Faire revenir oignons et poivrons 5 min.','Ajouter le bœuf, colorer 5 min.','Ajouter tomates, courgettes en dés, épices ; mijoter 25 min à couvert.','Servir avec le cheddar. Se réchauffe très bien 3 jours.']::text[],true,'seed'),
('r02-poulet-roti-et-legumes-du-four','Poulet rôti et légumes du four','poulet',60,3,10,42,560,array['batch','dimanche']::text[],'[{"name": "poulet entier", "qty": 1.6, "unit": "kg", "rayon": "Boucherie"}, {"name": "courgette", "qty": 3, "unit": "pièce", "rayon": "Légumes"}, {"name": "poivron", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon rouge", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "ail", "qty": 1, "unit": "tête", "rayon": "Légumes"}, {"name": "huile d''olive", "qty": 4, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "thym", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Four 200 °C. Poulet frotté d''huile, sel, thym, citron dans la cavité.','Légumes en gros morceaux autour, ail en chemise.','Rôtir 60 min, retourner les légumes à mi-cuisson.','Désosser les restes le soir même pour les lunchs.']::text[],true,'seed'),
('r03-curry-de-poulet-coco-epinards','Curry de poulet coco-épinards','poulet',30,3,9,40,540,array['batch','réchauffable']::text[],'[{"name": "hauts de cuisse de poulet", "qty": 1.2, "unit": "kg", "rayon": "Boucherie"}, {"name": "lait de coco", "qty": 800, "unit": "ml", "rayon": "Épicerie"}, {"name": "épinards frais", "qty": 400, "unit": "g", "rayon": "Légumes"}, {"name": "oignon", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "gingembre", "qty": 30, "unit": "g", "rayon": "Légumes"}, {"name": "pâte de curry", "qty": 3, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "huile de coco", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Revenir oignon et gingembre, ajouter la pâte de curry 1 min.','Ajouter le poulet en morceaux, colorer.','Verser le lait de coco, mijoter 20 min.','Ajouter les épinards 3 min avant la fin.']::text[],true,'seed'),
('r04-bolognaise-sur-courgetti','Bolognaise sur courgetti','boeuf',40,3,12,36,500,array['batch','réchauffable']::text[],'[{"name": "bœuf haché 5%", "qty": 900, "unit": "g", "rayon": "Boucherie"}, {"name": "tomates concassées", "qty": 800, "unit": "g", "rayon": "Épicerie"}, {"name": "courgette", "qty": 6, "unit": "pièce", "rayon": "Légumes"}, {"name": "carotte", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "ail", "qty": 3, "unit": "gousse", "rayon": "Légumes"}, {"name": "parmesan", "qty": 100, "unit": "g", "rayon": "Crèmerie"}, {"name": "origan", "qty": 1, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Sauce : oignon, ail, carotte fine, bœuf, tomates, origan ; 30 min.','Courgettes en spaghettis (spiraliseur ou économe).','Poêler les courgetti 2 min juste avant de servir, jamais à l''avance.','Lunch : sauce réchauffée + courgetti crus assaisonnés, ça tient très bien.']::text[],true,'seed'),
('r05-saumon-au-four-brocoli-citron','Saumon au four, brocoli citron','poisson',25,2,8,38,520,array['rapide','réchauffable']::text[],'[{"name": "pavé de saumon", "qty": 4, "unit": "pièce", "rayon": "Poissonnerie"}, {"name": "brocoli", "qty": 2, "unit": "tête", "rayon": "Légumes"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "huile d''olive", "qty": 3, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "aneth", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Four 200 °C. Brocoli en fleurettes huilé sur plaque, 10 min.','Ajouter les pavés, citron en rondelles, aneth ; 12 min.','Se mange aussi froid en lunch.']::text[],true,'seed'),
('r06-omelette-epinards-fromage','Omelette épinards-fromage','oeufs',10,1,4,30,430,array['rapide','lunch']::text[],'[{"name": "œufs", "qty": 6, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "épinards frais", "qty": 150, "unit": "g", "rayon": "Légumes"}, {"name": "gruyère râpé", "qty": 80, "unit": "g", "rayon": "Crèmerie"}, {"name": "beurre", "qty": 20, "unit": "g", "rayon": "Crèmerie"}]'::jsonb,array['Fondre les épinards au beurre 2 min.','Œufs battus, fromage, cuisson douce 4 min.','Plier, servir.']::text[],true,'seed'),
('r07-frittata-poivrons-chevre','Frittata poivrons-chèvre','oeufs',30,2,7,28,460,array['batch','lunch','froid']::text[],'[{"name": "œufs", "qty": 10, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "poivron", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "chèvre frais", "qty": 150, "unit": "g", "rayon": "Crèmerie"}, {"name": "crème", "qty": 100, "unit": "ml", "rayon": "Crèmerie"}, {"name": "huile d''olive", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Poivrons et oignon revenus 8 min dans une poêle allant au four.','Œufs battus + crème, verser, chèvre émietté.','Four 180 °C, 18 min. Excellent froid le lendemain.']::text[],true,'seed'),
('r08-boulettes-de-dinde-sauce-tomat','Boulettes de dinde sauce tomate','dinde',35,3,11,40,480,array['batch','réchauffable']::text[],'[{"name": "dinde hachée", "qty": 900, "unit": "g", "rayon": "Boucherie"}, {"name": "œuf", "qty": 1, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "parmesan", "qty": 80, "unit": "g", "rayon": "Crèmerie"}, {"name": "tomates concassées", "qty": 800, "unit": "g", "rayon": "Épicerie"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "ail", "qty": 3, "unit": "gousse", "rayon": "Légumes"}, {"name": "basilic", "qty": 1, "unit": "botte", "rayon": "Légumes"}, {"name": "haricots verts", "qty": 600, "unit": "g", "rayon": "Légumes"}]'::jsonb,array['Boulettes : dinde, œuf, parmesan, sel ; former, dorer 6 min.','Sauce tomate oignon-ail, boulettes dedans, 20 min.','Haricots verts vapeur 8 min à côté.']::text[],true,'seed'),
('r09-poelee-porc-brocoli-sesame','Poêlée porc-brocoli sésame','porc',25,2,9,36,490,array['rapide','réchauffable']::text[],'[{"name": "filet mignon de porc", "qty": 700, "unit": "g", "rayon": "Boucherie"}, {"name": "brocoli", "qty": 1, "unit": "tête", "rayon": "Légumes"}, {"name": "sauce soja", "qty": 4, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "graines de sésame", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "gingembre", "qty": 20, "unit": "g", "rayon": "Légumes"}, {"name": "ail", "qty": 2, "unit": "gousse", "rayon": "Légumes"}, {"name": "huile de sésame", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Porc en lamelles fines, saisir 4 min à feu vif, réserver.','Brocoli, ail, gingembre 5 min avec un fond d''eau.','Remettre le porc, soja, sésame, 2 min.']::text[],true,'seed'),
('r10-ratatouille-et-ufs-poches','Ratatouille et œufs pochés','vege',45,3,13,22,400,array['batch','végé']::text[],'[{"name": "aubergine", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "courgette", "qty": 3, "unit": "pièce", "rayon": "Légumes"}, {"name": "poivron", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "tomate", "qty": 6, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "ail", "qty": 4, "unit": "gousse", "rayon": "Légumes"}, {"name": "huile d''olive", "qty": 5, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "œufs", "qty": 6, "unit": "pièce", "rayon": "Crèmerie"}]'::jsonb,array['Légumes en dés, revenus séparément puis réunis, 35 min à feu doux.','Au moment de servir : 1 œuf poché par personne dans la ratatouille chaude.','Lunch : ratatouille froide + œuf dur.']::text[],true,'seed'),
('r11-salade-thon-avocat','Salade thon-avocat','poisson',10,1,7,32,480,array['rapide','lunch','froid']::text[],'[{"name": "thon au naturel", "qty": 2, "unit": "boîte", "rayon": "Épicerie"}, {"name": "avocat", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "concombre", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "tomates cerises", "qty": 200, "unit": "g", "rayon": "Légumes"}, {"name": "huile d''olive", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}]'::jsonb,array['Tout couper, mélanger, citron-huile, poivre.','Emporter l''avocat entier et le couper sur place s''il doit attendre.']::text[],true,'seed'),
('r12-cabillaud-en-papillote-courget','Cabillaud en papillote, courgettes','poisson',25,2,6,34,380,array['rapide','léger']::text[],'[{"name": "dos de cabillaud", "qty": 4, "unit": "pièce", "rayon": "Poissonnerie"}, {"name": "courgette", "qty": 3, "unit": "pièce", "rayon": "Légumes"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "tomates cerises", "qty": 250, "unit": "g", "rayon": "Légumes"}, {"name": "huile d''olive", "qty": 3, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "herbes de Provence", "qty": 1, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Four 200 °C. Courgettes en rubans dans le papier, poisson dessus.','Tomates, citron, huile, herbes ; fermer.','18 min. Ouvrir à table.']::text[],true,'seed'),
('r13-poulet-tikka-salade-de-concomb','Poulet tikka, salade de concombre','poulet',35,2,8,44,500,array['réchauffable','mariné']::text[],'[{"name": "hauts de cuisse de poulet", "qty": 800, "unit": "g", "rayon": "Boucherie"}, {"name": "yaourt grec", "qty": 300, "unit": "g", "rayon": "Crèmerie"}, {"name": "épices tikka", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "concombre", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "menthe", "qty": 1, "unit": "botte", "rayon": "Légumes"}, {"name": "oignon rouge", "qty": 1, "unit": "pièce", "rayon": "Légumes"}]'::jsonb,array['Mariner le poulet dans la moitié du yaourt + épices + citron (15 min à 24 h).','Four grill 220 °C, 20 min, ou poêle bien chaude.','Salade : concombre, oignon, menthe, reste de yaourt.']::text[],true,'seed'),
('r14-steak-hache-haricots-verts-a-l','Steak haché, haricots verts à l''ail','boeuf',20,1,6,40,470,array['rapide']::text[],'[{"name": "steak haché 5%", "qty": 2, "unit": "pièce", "rayon": "Boucherie"}, {"name": "haricots verts", "qty": 400, "unit": "g", "rayon": "Légumes"}, {"name": "ail", "qty": 2, "unit": "gousse", "rayon": "Légumes"}, {"name": "beurre", "qty": 30, "unit": "g", "rayon": "Crèmerie"}, {"name": "persil", "qty": 0.5, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Haricots vapeur 8 min.','Sauter au beurre avec l''ail 3 min, persil.','Steaks à la poêle selon cuisson.']::text[],true,'seed'),
('r15-shakshuka','Shakshuka','oeufs',25,2,12,24,420,array['végé','réchauffable']::text[],'[{"name": "œufs", "qty": 8, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "tomates concassées", "qty": 800, "unit": "g", "rayon": "Épicerie"}, {"name": "poivron rouge", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "ail", "qty": 3, "unit": "gousse", "rayon": "Légumes"}, {"name": "cumin", "qty": 1, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "feta", "qty": 150, "unit": "g", "rayon": "Crèmerie"}, {"name": "coriandre", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Base tomate-poivron-oignon-cumin, 15 min.','Creuser des nids, casser les œufs, couvrir 6 min.','Feta et coriandre. Lunch : base seule + œufs durs.']::text[],true,'seed'),
('r16-roti-de-porc-moutarde-choux-de','Rôti de porc moutarde, choux de Bruxelles','porc',70,3,9,42,560,array['batch','dimanche']::text[],'[{"name": "rôti de porc", "qty": 1.3, "unit": "kg", "rayon": "Boucherie"}, {"name": "moutarde", "qty": 3, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "choux de Bruxelles", "qty": 800, "unit": "g", "rayon": "Légumes"}, {"name": "lardons", "qty": 150, "unit": "g", "rayon": "Boucherie"}, {"name": "oignon", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "thym", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Four 180 °C. Rôti badigeonné de moutarde, thym, oignons autour ; 60 min.','Choux coupés en deux sautés aux lardons 12 min.','Tranches froides parfaites en lunch.']::text[],true,'seed'),
('r17-soupe-de-courgettes-au-chevre','Soupe de courgettes au chèvre','vege',30,3,9,14,260,array['batch','lunch','végé']::text[],'[{"name": "courgette", "qty": 6, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "bouillon de volaille", "qty": 1, "unit": "L", "rayon": "Épicerie"}, {"name": "chèvre frais", "qty": 200, "unit": "g", "rayon": "Crèmerie"}, {"name": "huile d''olive", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Oignon revenu, courgettes en rondelles, bouillon à hauteur, 20 min.','Mixer avec le chèvre.','Lunch à compléter d''une protéine : œufs durs, jambon ou reste de poulet.']::text[],true,'seed'),
('r18-crevettes-ail-persil-poelee-d','Crevettes ail-persil, poêlée d''épinards','poisson',15,1,5,34,380,array['rapide']::text[],'[{"name": "crevettes crues décortiquées", "qty": 400, "unit": "g", "rayon": "Poissonnerie"}, {"name": "ail", "qty": 4, "unit": "gousse", "rayon": "Légumes"}, {"name": "persil", "qty": 1, "unit": "botte", "rayon": "Légumes"}, {"name": "épinards frais", "qty": 300, "unit": "g", "rayon": "Légumes"}, {"name": "beurre", "qty": 30, "unit": "g", "rayon": "Crèmerie"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}]'::jsonb,array['Crevettes saisies 2 min par face au beurre-ail, persil, citron.','Épinards tombés dans la même poêle 2 min.']::text[],true,'seed'),
('r19-saute-de-buf-brocoli-soja','Sauté de bœuf brocoli-soja','boeuf',20,2,10,38,480,array['rapide','réchauffable']::text[],'[{"name": "bœuf à sauter (bavette)", "qty": 700, "unit": "g", "rayon": "Boucherie"}, {"name": "brocoli", "qty": 1, "unit": "tête", "rayon": "Légumes"}, {"name": "sauce soja", "qty": 4, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "ail", "qty": 3, "unit": "gousse", "rayon": "Légumes"}, {"name": "gingembre", "qty": 20, "unit": "g", "rayon": "Légumes"}, {"name": "huile de sésame", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "oignons nouveaux", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Bœuf en lamelles, saisir 2 min à feu très vif, réserver.','Brocoli 5 min avec ail-gingembre et un fond d''eau.','Réunir, soja, sésame, oignons nouveaux.']::text[],true,'seed'),
('r20-lasagnes-d-aubergine','Lasagnes d''aubergine','boeuf',60,3,13,36,540,array['batch','réchauffable']::text[],'[{"name": "bœuf haché 5%", "qty": 800, "unit": "g", "rayon": "Boucherie"}, {"name": "aubergine", "qty": 3, "unit": "pièce", "rayon": "Légumes"}, {"name": "tomates concassées", "qty": 800, "unit": "g", "rayon": "Épicerie"}, {"name": "ricotta", "qty": 400, "unit": "g", "rayon": "Crèmerie"}, {"name": "mozzarella râpée", "qty": 200, "unit": "g", "rayon": "Crèmerie"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "ail", "qty": 3, "unit": "gousse", "rayon": "Légumes"}, {"name": "basilic", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Aubergines en tranches fines grillées au four 15 min.','Sauce bolognaise rapide 15 min.','Monter : aubergine, sauce, ricotta ; mozzarella dessus. Four 180 °C, 30 min.']::text[],true,'seed'),
('r21-cuisses-de-poulet-roties-poivr','Cuisses de poulet rôties, poivrons','poulet',50,3,9,40,520,array['batch','réchauffable']::text[],'[{"name": "cuisses de poulet", "qty": 6, "unit": "pièce", "rayon": "Boucherie"}, {"name": "poivron", "qty": 4, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon rouge", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "paprika fumé", "qty": 1, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "huile d''olive", "qty": 3, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}]'::jsonb,array['Four 200 °C. Tout sur une plaque, huile, paprika, sel.','45 min, poivrons retournés à mi-cuisson.','Désosser 2 cuisses pour les lunchs.']::text[],true,'seed'),
('r22-tofu-croustillant-legumes-saut','Tofu croustillant, légumes sautés','vege',25,2,12,26,420,array['végé','rapide']::text[],'[{"name": "tofu ferme", "qty": 600, "unit": "g", "rayon": "Crèmerie"}, {"name": "brocoli", "qty": 1, "unit": "tête", "rayon": "Légumes"}, {"name": "poivron", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "courgette", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "sauce soja", "qty": 4, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "fécule de maïs", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "huile de sésame", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "ail", "qty": 2, "unit": "gousse", "rayon": "Légumes"}]'::jsonb,array['Tofu pressé, en cubes, fécule, poêle bien chaude 8 min.','Légumes sautés 6 min avec ail.','Réunir, soja, sésame.']::text[],true,'seed'),
('r23-salade-cesar-sans-croutons','Salade César sans croûtons','poulet',15,1,5,42,480,array['rapide','lunch','froid']::text[],'[{"name": "blanc de poulet", "qty": 400, "unit": "g", "rayon": "Boucherie"}, {"name": "laitue romaine", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "parmesan", "qty": 60, "unit": "g", "rayon": "Crèmerie"}, {"name": "œuf", "qty": 1, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "anchois", "qty": 4, "unit": "pièce", "rayon": "Épicerie"}, {"name": "huile d''olive", "qty": 3, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}]'::jsonb,array['Poulet grillé en tranches.','Sauce : jaune d''œuf, anchois écrasés, citron, huile montée.','Romaine, parmesan en copeaux.']::text[],true,'seed'),
('r24-gratin-de-courgettes-au-jambon','Gratin de courgettes au jambon','porc',40,3,10,30,480,array['batch','réchauffable']::text[],'[{"name": "courgette", "qty": 6, "unit": "pièce", "rayon": "Légumes"}, {"name": "jambon blanc", "qty": 300, "unit": "g", "rayon": "Boucherie"}, {"name": "œufs", "qty": 4, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "crème", "qty": 300, "unit": "ml", "rayon": "Crèmerie"}, {"name": "gruyère râpé", "qty": 200, "unit": "g", "rayon": "Crèmerie"}, {"name": "muscade", "qty": 1, "unit": "pincée", "rayon": "Épicerie"}]'::jsonb,array['Courgettes en rondelles fines, dégorgées 10 min au sel, épongées.','Couches courgettes-jambon, appareil œufs-crème-muscade, gruyère.','Four 180 °C, 30 min.']::text[],true,'seed'),
('r25-truite-aux-amandes-champignons','Truite aux amandes, champignons','poisson',20,1,6,36,470,array['rapide']::text[],'[{"name": "filet de truite", "qty": 2, "unit": "pièce", "rayon": "Poissonnerie"}, {"name": "amandes effilées", "qty": 40, "unit": "g", "rayon": "Épicerie"}, {"name": "champignons de Paris", "qty": 400, "unit": "g", "rayon": "Légumes"}, {"name": "beurre", "qty": 40, "unit": "g", "rayon": "Crèmerie"}, {"name": "citron", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "persil", "qty": 0.5, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Champignons sautés au beurre à feu vif 8 min.','Truite 3 min par face, amandes dorées dans le beurre, citron.']::text[],true,'seed'),
('r26-wraps-de-laitue-au-poulet','Wraps de laitue au poulet','poulet',15,1,6,38,420,array['rapide','lunch','froid']::text[],'[{"name": "blanc de poulet", "qty": 400, "unit": "g", "rayon": "Boucherie"}, {"name": "laitue iceberg", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "avocat", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "mayonnaise", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "moutarde", "qty": 1, "unit": "c. à c.", "rayon": "Épicerie"}, {"name": "cornichons", "qty": 4, "unit": "pièce", "rayon": "Épicerie"}]'::jsonb,array['Poulet poché ou grillé, effiloché, lié à la mayo-moutarde, cornichons hachés.','Grandes feuilles d''iceberg comme wraps, avocat en tranches.','Emporter feuilles et garniture séparément.']::text[],true,'seed'),
('r27-soupe-de-poulet-aux-legumes','Soupe de poulet aux légumes','poulet',40,3,8,32,340,array['batch','lunch','réchauffable']::text[],'[{"name": "hauts de cuisse de poulet", "qty": 800, "unit": "g", "rayon": "Boucherie"}, {"name": "poireau", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "céleri branche", "qty": 3, "unit": "pièce", "rayon": "Légumes"}, {"name": "carotte", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "bouillon de volaille", "qty": 1.5, "unit": "L", "rayon": "Épicerie"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "thym", "qty": 1, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Poulet et légumes en morceaux, bouillon, thym ; 30 min.','Effilocher le poulet, remettre.','Congèle bien par portions.']::text[],true,'seed'),
('r28-buf-bourguignon-aux-champignon','Bœuf bourguignon aux champignons','boeuf',120,3,9,44,580,array['batch','dimanche']::text[],'[{"name": "bœuf à braiser (paleron)", "qty": 1.3, "unit": "kg", "rayon": "Boucherie"}, {"name": "lardons", "qty": 200, "unit": "g", "rayon": "Boucherie"}, {"name": "champignons de Paris", "qty": 500, "unit": "g", "rayon": "Légumes"}, {"name": "oignon", "qty": 2, "unit": "pièce", "rayon": "Légumes"}, {"name": "vin rouge", "qty": 500, "unit": "ml", "rayon": "Épicerie"}, {"name": "bouillon de bœuf", "qty": 300, "unit": "ml", "rayon": "Épicerie"}, {"name": "ail", "qty": 3, "unit": "gousse", "rayon": "Légumes"}, {"name": "bouquet garni", "qty": 1, "unit": "pièce", "rayon": "Légumes"}]'::jsonb,array['Colorer le bœuf en cubes, réserver. Lardons, oignons.','Déglacer au vin, bouillon, bouquet garni ; 1 h 45 à couvert.','Champignons sautés ajoutés les 15 dernières minutes. Meilleur réchauffé.']::text[],true,'seed'),
('r29-ufs-brouilles-saumon-fume-avoc','Œufs brouillés, saumon fumé, avocat','oeufs',10,1,5,30,500,array['rapide','lunch']::text[],'[{"name": "œufs", "qty": 6, "unit": "pièce", "rayon": "Crèmerie"}, {"name": "saumon fumé", "qty": 120, "unit": "g", "rayon": "Poissonnerie"}, {"name": "avocat", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "beurre", "qty": 20, "unit": "g", "rayon": "Crèmerie"}, {"name": "ciboulette", "qty": 0.5, "unit": "botte", "rayon": "Légumes"}]'::jsonb,array['Œufs brouillés doux au beurre.','Saumon en lanières, avocat, ciboulette.']::text[],true,'seed'),
('r30-poelee-de-dinde-courgettes-cur','Poêlée de dinde courgettes-curry','dinde',20,2,8,40,440,array['rapide','réchauffable']::text[],'[{"name": "escalope de dinde", "qty": 700, "unit": "g", "rayon": "Boucherie"}, {"name": "courgette", "qty": 4, "unit": "pièce", "rayon": "Légumes"}, {"name": "oignon", "qty": 1, "unit": "pièce", "rayon": "Légumes"}, {"name": "curry en poudre", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}, {"name": "crème", "qty": 200, "unit": "ml", "rayon": "Crèmerie"}, {"name": "huile d''olive", "qty": 2, "unit": "c. à s.", "rayon": "Épicerie"}]'::jsonb,array['Dinde en lanières saisie 4 min, réserver.','Oignon et courgettes en dés 6 min.','Remettre la dinde, curry, crème, 3 min.']::text[],true,'seed')
on conflict (id) do nothing;
